# パネルデータ分析 {-#panel}

データを読み込み，必要な加工をします．

```{r}
mydata <- read.csv("yamaguchi.csv")

mydata2 <- subset(mydata, year > 1995 & hh.type == "all")
```


## 実証例 6.1 {-}

固定効果推定を行うためには`{plm}`パッケージの`plm()`関数が便利です

```{r collapse=T}
library(plm)

model1 <- plm(emp.rate ~ cap.rate + pref,
                      data = mydata2,
                      index = c("pref"),
                      model = "pooling")
model1$coefficients[2]
```


## 実証例 6.2 {-}

```{r collapse=T}
library(plm)
library(AER)

model1 <- plm(emp.rate ~ cap.rate + pref,
                      data = mydata2,
                      index = c("pref"),
                      model = "pooling")
result1 <- coeftest(model1, vcov = vcovHC(model1, type = "HC1", 
                                          cluster = "group"))
options(scipen = 1)
round(result1[2, ], 7)
```

標準誤差が教科書の値とは一致しません．教科書の値はStataによって出力されていますが，Stataのクラスター構造に頑健な標準誤差は少し計算の仕方が異なるからです^[https://stackoverflow.com/questions/33155638/clustered-standard-errors-in-r-using-plm-with-fixed-effects を参照．]．`{estimatr}`パッケージを用いると簡単にStataの出力を再現できます．

```{r collapse=T}
library(estimatr)
library(AER)

result2 <- lm_robust(emp.rate ~ cap.rate + pref,
          data = mydata2,
          clusters = pref,
          se_type = "stata")
result2
```

## 実証例 6.3 {-}

```{r collapse=T}
library(plm)
library(AER)

model1 <- plm(emp.rate ~ cap.rate + pref,
                      data = mydata2,
                      index = c("pref"),
                      model = "pooling")
result1 <- coeftest(model1, vcov = vcovHC(model1, type = "HC1", 
                                          cluster = "group"))
options(scipen = 1)
```
