# 操作変数法 {-#iv}

```{r message=FALSE, warning=FALSE, collapse=T}
library(AER)

mydata <- read.csv("ipehd_qje2009_master.csv")
```

## 実証例 7.1 {-}

固定効果推定を行うためには`{AER}`パッケージの`ivreg()`関数が便利です

```{r collapse=T}
ols1 <- lm(f_rw ~ f_prot, mydata) # OLS
coeftest(ols1, vcov. = vcovHC, type = "HC1")

iv1 <- ivreg(f_rw ~ f_prot | kmwittenberg, data = mydata) # IV
iv1
```

## 実証例 7.2 {-}

```{r collapse=T}
iv2 <- ivreg(f_rw ~ f_prot | kmwittenberg, data = mydata) # IV
coeftest(iv2, vcov. = vcovHC, type = "HC1")
```

## 実証例 7.3 {-}

```{r collapse=T}
iv3 <- ivreg(f_rw ~  f_prot + f_young + f_jew + f_fem + f_ortsgeb + f_pruss + hhsize + lnpop + gpop + f_blind + f_deaf + f_dumb + f_miss | kmwittenberg + f_young + f_jew + f_fem + f_ortsgeb + f_pruss + hhsize + lnpop + gpop + f_blind + f_deaf + f_dumb + f_miss, data = mydata) # IV
coeftest(iv3, vcov. = vcovHC, type = "HC1")
```

## 実証例 7.4 {-}

```{r collapse=T}
fs <- lm(f_prot ~ kmwittenberg + f_young + f_jew + f_fem + f_ortsgeb + f_pruss + hhsize + lnpop + gpop + f_blind + f_deaf + f_dumb + f_miss, data = mydata) # first-stage
coeftest(fs, vcov. = vcovHC, type = "HC1")

beta1_hat <- round(coeftest(fs, vcov. = vcovHC, type = "HC1")["kmwittenberg", "Estimate"], 3)
se <- round(coeftest(fs, vcov. = vcovHC, type = "HC1")["kmwittenberg", "Std. Error"], 3)
t_value <- beta1_hat / se
f_value <- t_value ^ 2

f_value
```

```{r collapse=T}
fs2 <- lm(f_prot ~ kmwittenberg + (kmwittenberg * lnpop) + (kmwittenberg * gpop) + f_young + f_jew + f_fem + f_ortsgeb + f_pruss + hhsize + lnpop + gpop + f_blind + f_deaf + f_dumb + f_miss, data = mydata) # first-stage with interaction

coeftest(fs2, vcov. = vcovHC, type = "HC1")
```

```{r collapse=T}
linearHypothesis(fs2, c("kmwittenberg = 0", "kmwittenberg:lnpop = 0", "kmwittenberg:gpop = 0"), white.adjust = "hc1")
```

## 実証例 7.5 {-}

```{r collapse=T}
iv4 <- ivreg(f_rw ~ f_prot + f_young + f_jew + f_fem + f_ortsgeb + f_pruss + hhsize + lnpop + gpop + f_blind + f_deaf + f_dumb + f_miss | kmwittenberg +  (kmwittenberg * lnpop) + (kmwittenberg * gpop) + f_young + f_jew + f_fem + f_ortsgeb + f_pruss + hhsize + lnpop + gpop + f_blind + f_deaf + f_dumb + f_miss, data = mydata)

linearHypothesis(lm(residuals(iv4) ~ kmwittenberg + (kmwittenberg * lnpop) + (kmwittenberg * gpop) + f_young + f_jew + f_fem + f_ortsgeb + f_pruss + hhsize + lnpop + gpop + f_blind + f_deaf + f_dumb + f_miss, data = mydata), c("kmwittenberg", "kmwittenberg:lnpop = 0", "kmwittenberg:gpop = 0"), test= "Chisq")

linearHypothesis(lm(residuals(iv4) ~ kmwittenberg + (kmwittenberg * lnpop) + (kmwittenberg * gpop) + f_young + f_jew + f_fem + f_ortsgeb + f_pruss + hhsize + lnpop + gpop + f_blind + f_deaf + f_dumb + f_miss, data = mydata), c("kmwittenberg", "kmwittenberg:lnpop = 0", "kmwittenberg:gpop = 0"), test= "Chisq", white.adjust = "hc1")
```

